name: PS5 Stock Checker

on:
  schedule:
    - cron: "*/2 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Check PS5 stock
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python stock_checker.py

      - name: Save restock log
        run: |
          if [ -f restocks.log ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add restocks.log
            git diff --cached --quiet || git commit -m "Update restock log"
            git push
          fi
